export const routePaths = {
  account: '/cms/account',
  adminEntitlements: '/cms/admin/entitlements',
  adminFeatures: '/cms/admin/features',
  adminMenus: '/cms/admin/menus',
  adminPermissions: '/cms/admin/permissions',
  adminPlans: '/cms/admin/plans',
  adminRoles: '/cms/admin/roles',
  adminSubscriptions: '/cms/admin/subscriptions',
  adminUsers: '/cms/admin/users',
  automationDevices: '/cms/automation/devices',
  automationExecutions: '/cms/automation/executions',
  automationLogs: '/cms/automation/logs',
  automationScenarios: '/cms/automation/scenarios',
  billing: '/cms/billing',
  cms: '/cms',
  cmsOverview: '/cms/overview',
  forgotPassword: '/forgot-password',
  landing: '/',
  login: '/login',
  mediaHistory: '/cms/media/history',
  register: '/register',
  resetPassword: '/reset-password',
  settings: '/cms/settings',
  usage: '/cms/usage',
  videoDownloader: '/video-downloader',
} as const;

export type RoutePath = (typeof routePaths)[keyof typeof routePaths];
